Added telemetry functionality for mission control
huskyroboticsteam/mission-control pull request #13
Opened 2023-02-10 02:59 UTC by vvarun77

Added `teleSlice.js` and `telemetryMiddleware.js` to mission control for storing and receiving telemetry data relating to the rover's orientation and position.

2023-02-10 03:07 UTC, abhaybd requested changes
Overall pretty good! Had some minor issues regarding documentation and some naming. Also, can we rename `teleSlice.js` to `telemetrySlice.js`? It's more readable and explicit.

2023-02-10 03:07 UTC, abhaybd commented on README.md
> +- `posZ` - refers to the Z position of the rover in world reference frame
I think you forgot to add the time field to the documentation as well

2023-02-10 03:07 UTC, abhaybd commented on src/store/middleware/telemetryMiddleware.js
> +            timestamp
Can we name this something else? Like we discussed, this isn't going to be timestamp, it'll be something more like data age or recency.

2023-02-10 03:07 UTC, abhaybd commented on src/store/teleSlice.js
> +const teleSlice = createSlice({
`tele` is an awkward prefix. Can we call this `telemetrySlice`? It's not *that* long and it's more explicit.

2023-02-10 22:08 UTC, abhaybd requested changes
Looks better, just a minor change needed about the documentation.

I'm not too familiar with redux, so I couldn't entirely say if the changes to the `store.js` are needed, so I'll defer that to Kyle. I'd say fix the documentation issue and get a final signoff from Kyle and then merge it.

2023-02-10 22:08 UTC, abhaybd commented on README.md
> +- `recency` - refers to the difference in time between when the message was sent and received
This description isn't quite right, that would be something closer to latency. Recency measures the amount of elapsed time between the value being measured and being sent from the rover.

2023-02-11 07:46 UTC, abhaybd requested changes
One minor thing I forgot!

2023-02-11 07:46 UTC, abhaybd commented on README.md
> +- `recency` - refers to the difference in time between when the measurement was taken and sent
Should have mentioned this before, but we need units. For `posX`, `posY`, and `pozZ` can we specify they're in meters, and `recency` is in seconds?

2023-02-14 08:39 UTC, KyleR56 approved these changes
Looks good aside from some small changes which I just made myself in a new commit (I also fixed some small style issues I found in other files). There might be a slight naming inconsistency with "telemetry" and "roverPosition". The two names are used interchangeably, so we might want to just use 1 of them for consistency. But I don't think it's a big deal so I'll leave it up in the air.

2023-02-16 05:40 UTC, abhaybd approved these changes
Looks good!

2023-02-16 05:40 UTC, merged