Full-Resolution Camera Downloads
huskyroboticsteam/mission-control pull request #71
Opened 2024-07-18 06:17 UTC by Geeoon

Currently, clicking the download button will just download the client-side H264 compressed stream, which is fairly low quality. This PR adds the ability to request full-resolution jpg images from the rover, and if the camera is available, a base64 encoded image will be sent to mission control at a much higher resolution than the normal client-side video stream.  Related to https://github.com/huskyroboticsteam/Resurgence/pull/331

2024-07-18 08:16 UTC, abhaybd requested changes
Overall good stuff, some comments

2024-07-18 08:16 UTC, abhaybd commented on src/store/middleware/camerasMiddleware.js
> +        if (message.data !== "") {
Should be combined into `else if (message.type === ... && message.data === ...)`

2024-07-18 08:16 UTC, abhaybd commented on src/store/middleware/camerasMiddleware.js
> +
Trailing empty line

2024-07-18 08:16 UTC, abhaybd commented on README.md
> +  data: string | null
Under what circumstances would `data` be null? If there's no data, is it simpler to just not send back a camera frame report?

2024-07-20 05:38 UTC, abhaybd requested changes
Very minor change needed. Besides that, this looks good and I'll test and merge this when I'm back in town in a couple weeks.

2024-07-20 05:38 UTC, abhaybd commented on README.md
> +Sent from Mission Control to instruct the rover server to send a Camera Frame Report.
Super minor, but mention how this works with the report. I.e. "If camera specifies a valid camera stream, the rover will respond with a camera frame report containing the latest frame from that camera."

2025-02-08 19:34 UTC, huttongrabiel approved these changes

2025-02-08 19:43 UTC, merged