add a visual indicator which shows the status of robot's navigation
huskyroboticsteam/mission-control pull request #76
Opened 2024-11-16 21:23 UTC by ARRYTHEBEAST

The nav Status div is below opMode Select and it shows either navigating or Destination reached depending on the status.

2025-01-14 03:02 UTC, ARRYTHEBEAST commented on src/components/navigation/OpModeSelect.jsx
> -        Current operation mode: <span className={`op-mode-select__op-mode op-mode-select__op-mode--${opMode}`}>{opMode}</span>
revert

2025-01-14 03:02 UTC, ARRYTHEBEAST commented on src/components/navigation/OpModeSelect.jsx
> -      <button onClick={handleClick} >
revert

2025-01-14 03:03 UTC, ARRYTHEBEAST reviewed
revert unneccessary changers

2025-01-19 00:39 UTC, huttongrabiel submitted a review, later dismissed

2025-01-19 00:39 UTC, huttongrabiel commented on src/components/navigation/NavigationStatus.jsx
> +const APPROACHING_THRESHOLD = POSITION_THRESHOLD * 3;
Like we talked about lets use the existing distance for this. see [here](https://github.com/huskyroboticsteam/Resurgence/blob/ad9e206dc851606d533bf1b7fdde6771d90306d5/src/Constants.cpp#L157)

2025-01-19 01:03 UTC, ARRYTHEBEAST commented on src/components/navigation/NavigationStatus.jsx
> +const APPROACHING_THRESHOLD = POSITION_THRESHOLD * 3;
Thank you, the changes have been made

2025-01-25 18:48 UTC, imisaacwu requested changes
Few small things, waypoint nav updating works, nice!

2025-01-25 18:48 UTC, imisaacwu commented on src/components/navigation/NavigationStatus.css
> +.nav-status {
Make sure your tabs/indents are consistent please

2025-01-25 18:48 UTC, imisaacwu commented on src/components/navigation/NavigationStatus.jsx
> +const POSITION_THRESHOLD = 0.5;
Consider moving these into the constants/ folder, maybe a new file like `navigationConstants.js`

2025-01-25 18:48 UTC, imisaacwu commented on src/components/navigation/NavigationStatus.jsx
> +    return num >= 0 ? " " + ret : ret;
Maybe remove the space in the sanitization here? This results in coordinates being displayed like ( x, y)
Could just remove the space here and insert it in line 75 where it's being displayed

2025-01-25 18:48 UTC, imisaacwu commented on src/components/navigation/OpModeSelect.css
> -.op-mode-select > p {
Revert your changes in this file, have a space around the '>'

2025-01-25 18:48 UTC, imisaacwu commented on src/components/navigation/OpModeSelect.jsx
> -        Current operation mode: <span className={`op-mode-select__op-mode op-mode-select__op-mode--${opMode}`}>{opMode}</span>
Remember to revert this

2025-01-25 18:48 UTC, imisaacwu commented on src/store/waypointNavSlice.js
> +export const selectLatitude = state => state.waypointNav.latitude;
Is this necessary?

2025-02-01 20:53 UTC, imisaacwu approved these changes
lgtm

2025-02-01 20:54 UTC, merged